### ISSUE TITLE
Example usage in code documentation throws Attribute error

### ISSUE THREAD

**Issue by StephenTerry** [matteoferla/DnD-battler#6]
When I try to use the example in the code documentation I get the following error:

```
level1 = DnD.Creature("buff peseant",base='commoner',abilities = {'str': 15,'dex': 14,'con':13,'int':12,'wis':10,'cha': 8}, alignment ="good", attack_parameters='longsword')

Warning (from warnings module):
  File "DnD.py", line 384
    warnings.warn('Insufficient info: defaulting hit dice to d8')
UserWarning: Insufficient info: defaulting hit dice to d8

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    level1 = DnD.Creature("buff peseant",base='commoner',abilities = {'str': 15,'dex': 14,'con':13,'int':12,'wis':10,'cha': 8}, alignment ="good", attack_parameters='longsword')
  File "DnD.py", line 289, in __init__
    self._initialise(name=wildcard, **kwargs)
  File "DnD.py", line 366, in _initialise
    self.hd = Dice(self.ability_bonuses['con'], int(self.settings['hd']), avg=True, role="hd")
AttributeError: Dice instance has no attribute '__trunc__'
```

Adding hit dice as a keyword argument solves this issue:

```
level1 = DnD.Creature("buff peseant",base='commoner',abilities = {'str': 15,'dex': 14,'con':13,'int':12,'wis':10,'cha': 8}, alignment ="good", attack_parameters='longsword',hd=2)
```

**Comment by matteoferla** [comment]
I cannot seem to replicate this behaviour and I do not understand why it happens —Unicode? Gremlins? The [server](http://battle-matteoferla.rhcloud.com/) for this crashes occassionally for no clear reason...

However, I did spot a bug when a creature was based off another (example below).

The code should know a longsword is a d8 and it does in my case and it seems to be okay with some other weapons.

> > > level1 = DnD.Creature("buff peseant",base='commoner',abilities = {'str': 15,'dex': 14,'con':13,'int':12,'wis':10,'cha': 8}, alignment ="good", attack_parameters='greatsword')
> > > str(level1.attacks[0]['damage'])
> > > 'd12+0'
> > > Note that the bonus is wrong as mentioned. Now it shows
> > > 'd12+2'

I'll try and see more later if I can replicate the issue.

**Comment by StephenTerry** [comment]
Part of the problem may be that I did not realize it was a Python 3 script and was running it in 2.7.

**Comment by matteoferla** [comment]
That also explains the unicode issue. All good then —I really ought to run `3to2` on it.
